[package]
name = "train_route_explorer"
version = "0.1.0"
edition = "2021"
description = "Client-side GTFS route timeline explorer."
license = "MIT"
repository = "https://github.com/bbodin/train-route-explorer"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
csv = "1.3"
wasm-bindgen = "0.2"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
